### ISSUE TITLE
Logging of each compiled template slows task down

### ISSUE THREAD

**Issue by jasonmerino** [STAH/grunt-dustjs#18]
Logging each of the compiled template paths down may only slow the task down a little, but this task runs quite often in one of my projects. I think adding an option to supress any output until templates are finished would be a good option to add. Thoughts?

I wouldn't mind adding it and submitting a pull request if you are interested.

**Comment by STAH** [comment]
Implemented in #15

**Comment by jasonmerino** [comment]
:+1: :tada: :+1:
